namespace Senior_Project.Models
{
    /// <summary>
    /// Keeps track of errors, this was generated by visual studio 
    /// </summary>
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}
